export const merchItems = [
  {
    name: "Свитшот Tesla",
    price: 233,
    state: true,
    image: "images/TeslaY_Card.jpg",
    availability: true,
    description: "Описание товарарарарарарар Описание товарарарарарарар  ",
    type: "Какой-то тип",
    material: "Ангорка",
  },
  {
    name: "Наклейка Tesla",
    price: 150,
    state: true,
    image: "images/TeslaY_Card.jpg",
    availability: false,
    description: "Описание товарарарарарарар Описание товарарарарарарар  ",
    type: "Какой-то тип",
    material: "Ангорка",
  },
  {
    name: "Футболка Tesla",
    price: 344,
    state: true,
    image: "images/TeslaY_Card.jpg",
    availability: true,
    description: "Описание товарарарарарарар Описание товарарарарарарар  ",
    type: "Какой-то тип",
    material: "Ангорка",
  },
  {
    name: "Куртка Tesla",
    price: 411,
    state: true,
    image: "images/TeslaY_Card.jpg",
    availability: false,
    description: "Описание товарарарарарарар Описание товарарарарарарар  ",
    type: "Какой-то тип",
    material: "Ангорка",
  },
  {
    name: "Блокнот Tesla",
    price: 634,
    state: true,
    image: "images/TeslaY_Card.jpg",
    availability: true,
    description: "Описание товарарарарарарар Описание товарарарарарарар  ",
    type: "Какой-то тип",
    material: "Ангорка",
  },
  {
    name: "Брелок Tesla",
    price: 132,
    state: true,
    image: "images/TeslaY_Card.jpg",
    availability: false,
    description: "Описание товарарарарарарар Описание товарарарарарарар  ",
    type: "Какой-то тип",
    material: "Ангорка",
  },
];
