export const modelsData = {
  modelS: {
    name: "Model S",
    value1: "396 mi",
    desc1: "Запас ходу",
    value2: "1.99 с",
    desc2: "0 - 100 км/г",
    value3: "200 mph",
    desc3: "Макс швидкість",
    value4: "1,020 hp",
    desc4: "Пікова потужність",
  },
  modelSru: {
    name: "Model S",
    value1: "396 mi",
    desc1: "Запас хода",
    value2: "1.99 с",
    desc2: "0 - 100 км/ч",
    value3: "200 mph",
    desc3: "Макс. скорость",
    value4: "1,020 hp",
    desc4: "Пиковая мощность",
  },

  model3: {
    name: "Model 3",
    value1: "3.1 с",
    desc1: "0 - 100 км/г",
    value2: "358 mi",
    desc2: "Запас ходу",
    value3: "AWD",
    desc3: "Двухдвигунний",
    color: "white",
  },
  model3ru: {
    name: "Model 3",
    value1: "3.1 с",
    desc1: "0 - 100 км/ч",
    value2: "358 mi",
    desc2: "Запас хода",
    value3: "AWD",
    desc3: "Двухдвигательный",
    color: "white",
  },

  modelX: {
    name: "Model X",
    value1: "333 mi",
    desc1: "Запас ходу",
    value2: "2.5 с",
    desc2: "0 - 100 км/г",
    value3: "9.9 с",
    desc3: "1/4 mile",
    value4: "1.020 hp",
    desc4: "Пікова потужність",
  },
  modelXru: {
    name: "Model X",
    value1: "333 mi",
    desc1: "Запас хода",
    value2: "2.5 с",
    desc2: "0 - 100 км/ч",
    value3: "9.9 с",
    desc3: "1/4 mile",
    value4: "1.020 hp",
    desc4: "Пиковая мощность",
  },

  modelY: {
    name: "Model Y",
    value1: "76 cu ft",
    desc1: "Cargo Space",
    value2: "330 mi",
    desc2: "Запас ходу",
    value3: "AWD",
    desc3: "Двухдвигунний",
    color: "white",
  },
  modelYru: {
    name: "Model Y",
    value1: "76 cu ft",
    desc1: "Cargo Space",
    value2: "330 mi",
    desc2: "Запас хода",
    value3: "AWD",
    desc3: "Двухдвигательный",
    color: "white",
  },

  roadster: {
    name: "Roadster",
    value1: "1.9 с",
    desc1: "0 - 100 км/г",
    value2: "+250 mph",
    desc2: "Макс Швидкість",
    value3: "AWD",
    desc3: "Двухдвигунний",
    color: "white",
  },
  roadsterru: {
    name: "Roadster",
    value1: "1.9 с",
    desc1: "0 - 100 км/г",
    value2: "+250 mph",
    desc2: "Макс Скорость",
    value3: "AWD",
    desc3: "Двухдвигательный",
    color: "white",
  },

  cybertruck: {
    name: "Cybertruck",
    value1: "",
    desc1: "",
    value2: "",
    desc2: "",
    value3: "",
    desc3: "",
  },
};
